/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Estructuras;

import static Estructuras.MenuInicial.grafo;
import javax.swing.JOptionPane;
import org.graphstream.graph.Graph;
import org.graphstream.graph.implementations.SingleGraph;

/**
 *
 * @author
 */
public class AlcanceDeSucursal extends javax.swing.JFrame {

    public static Grafo grafo;
    public FuncionesSucursal funciones;
    public Lista visitados;

    /**
     * Creates new form AlcanceDeSucursal
     */
    public AlcanceDeSucursal(Grafo grafo) {
        initComponents();
        this.visitados = null;
        this.setVisible(true);

        this.grafo = grafo;
        this.funciones = new FuncionesSucursal(this.grafo);

        String[] estaciones = new String[this.grafo.max];
        for (int i = 0; i < this.grafo.max; i++) {
            estaciones[i] = "";
        }
        for (int i = 0; i < this.grafo.max; i++) {
            if (this.grafo.vertices[i].esSucursal) {
                estaciones[i] = this.grafo.vertices[i].nombreEstacion;
            }
        }
        for (int i = 0; i < this.grafo.max; i++) {
            if (!estaciones[i].equals("")) {
                this.jComboBox1.addItem(estaciones[i]);
            }
        }
    }
    
    public static void graf(Lista lista) {
    // Crear un grafo de ejemplo
    Graph graph = new SingleGraph("Ejemplo de Grafo");
    
    // Añadir nodos
    for (int i = 0; i < grafo.max; i++) {
        if (!grafo.vertices[i].nombreEstacion.equals("")) {
            graph.addNode(grafo.vertices[i].nombreEstacion);
            graph.getNode(grafo.vertices[i].nombreEstacion).setAttribute("ui.label", grafo.vertices[i].nombreEstacion); // Establecer el nombre del nodo
            graph.getNode(grafo.vertices[i].nombreEstacion).setAttribute("ui.style", "fill-color: blue;"); // Color de los nodos
        }
    }
    
    // Añadir aristas
    for (int i = 0; i < grafo.max; i++) {
        if (!grafo.vertices[i].nombreEstacion.equals("")) {
            NodoEstacion aux = grafo.vertices[i].adyacentes.primero;
            while(aux != null){
                try {
                    graph.addEdge(grafo.vertices[i].nombreEstacion + aux.estacion.nombreEstacion, 
                                   grafo.vertices[i].nombreEstacion, 
                                   aux.estacion.nombreEstacion);
                } catch(Exception e) {
                    // Manejo de excepciones si es necesario
                }
                aux = aux.sig;
            }
        }
    }
    
    NodoEstacion temp = lista.primero;
    while(temp!= null){
         graph.getNode(temp.estacion.nombreEstacion).setAttribute("ui.style", "fill-color: red;"); 
         
         temp = temp.sig;
    }
             graph.getNode(lista.primero.estacion.nombreEstacion).setAttribute("ui.style", "fill-color: green;"); 

    // Establecer propiedades de visualización
    graph.setAttribute("ui.stylesheet",
            "node { size: 10px; text-alignment: under; } " + // Tamaño de los nodos
            "node.label { fill-color: white; size: 20px; } " + // Color y tamaño de la etiqueta
            "edge { fill-color: gray; }");

    // Ajustar el layout para evitar superposición
    graph.setAttribute("ui.quality");
    graph.setAttribute("ui.antialias");
    graph.setAttribute("ui.layout", "force");
    graph.setAttribute("ui.layout.force.springLength", 100); // Distancia entre nodos
    graph.setAttribute("ui.layout.force.springConstant", 0.1); // Constante de resorte

    // Crear un Viewer para mostrar el grafo
    System.setProperty("org.graphstream.ui", "swing");
    graph.display();
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ALCANCE DE SUCURSAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jComboBox1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 200, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 430, 210));

        jButton3.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton3.setText("VER ALCANCE (BFS)");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("PARADAS ALCANZADAS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jButton4.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton4.setText("ATRAS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        jButton5.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton5.setText("VER EN GRAFO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, -1));

        jLabel6.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SUCURSALES");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jButton6.setFont(new java.awt.Font("Nirmala UI", 1, 24)); // NOI18N
        jButton6.setText("VER ALCANCE (DFS)");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        GestionSucursales m = new GestionSucursales(grafo);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try{
         visitados = this.funciones.profundidad(this.jComboBox1.getSelectedItem().toString());
        this.jTextArea1.setText(visitados.imprimir());
        }catch(Exception e){
            System.out.println(e);
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
             visitados = this.funciones.amplitud(this.jComboBox1.getSelectedItem().toString());
            this.jTextArea1.setText(visitados.imprimir());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try{
            graf(visitados);
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "DEBES HACER UN RECORRIDO PARA GRAFICAR");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlcanceDeSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlcanceDeSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlcanceDeSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlcanceDeSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlcanceDeSucursal(grafo).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
